fn_map = {
    "Download Image": "downloadImagesToDrive",
    "Create Thumbnail": "copyResizeImageAndStoreUrl",
    "Describe Image": "processImagesWithOpenAI",
    "Add Mockups": "updateImagesFromMockupFolders",
    "Upscale Image": "copyUpscaleImageAndStoreVariants",
    "Generate Mockup JSON": "generateMockupJson",
    "Upload Files": "uploadDigitalFiles",
    "Upload Images": "uploadImageAssets",
    "Vectorize": "vectorizeSourceSvg",
    "Create Description": "findReplaceInDescription",
    "Create Folder": "processCreateFolders",
    "Rename Files": "updateFileNamesWithImageName",
    "Move Files": "moveFilesAndImagesToFolder",
    "Generate Mockups": "generateMockupsFromDrive",
    "Create JSON": "buildMockupJsonFromFolderStructure",
    "Create PDF": "processCreatePDF",
    "Suggest Next Action": "suggest_next_action_for_row",
    "Update Image Metadata": "updateImageMetadata",
    "Generate XY": "generateXYFromSample",
    "Write Thinking": "writeToThinkingTab",
    "Write Log": "writeToLog",
    "Update Status": "updateRowStatus",
    "Archive Row": "archiveRow",
    "Log Error": "updateRowError"
}
